name: Mobile Build

on:
  push:
    branches:
      - main

jobs:

  android:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add Android Target
        run: rustup target add aarch64-linux-android

      - name: Install cargo-apk
        run: cargo install cargo-apk

      - name: Build Android APK
        run: cargo apk build --release

  ios:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Add iOS Target
        run: rustup target add aarch64-apple-ios

      - name: Build iOS
        run: cargo build --release --target aarch64-apple-ios