name: slint-calculator build

on:
  push:
    branches: [ main ]

jobs:

  windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: windows
          path: target/release/*.exe

  macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: macos
          path: target/release/*

  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo build --release
      - uses: actions/upload-artifact@v4
        with:
          name: linux
          path: target/release/*

  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add aarch64-linux-android
      - run: cargo install cargo-apk
      - run: cargo apk build --release
      - uses: actions/upload-artifact@v4
        with:
          name: android-apk
          path: target/android-artifacts/**/*.apk

  ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: rustup target add aarch64-apple-ios
      - run: cargo build --release --target aarch64-apple-ios
      - uses: actions/upload-artifact@v4
        with:
          name: ios
          path: target/aarch64-apple-ios/release/*